courbet: hidl: add missing nxpnfc interface into compatibility matrix
error: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
checkvintf E 01-23 04:40:16 78306 78306 check_vintf.cpp:620]     vendor.nxp.nxpnfc@1.0::INxpNfc/default